name: test-mac-build-latest
on:
  workflow_dispatch:
    inputs:
      target:
        description: 'MACOSX_DEPLOYMENT_TARGET'
        required: true
jobs:
  mac-build:
    continue-on-error: true
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build watchman
        run: "SDKROOT=$(xcrun --show-sdk-path) python3 build/fbcode_builder/getdeps.py --allow-system-packages build --src-dir=. watchman  --project-install-prefix watchman:/usr/local"
        env:
          MACOSX_DEPLOYMENT_TARGET: ${{ github.event.inputs.target }}
      - name: Copy artifacts
        run: "python3 build/fbcode_builder/getdeps.py --allow-system-packages fixup-dyn-deps --src-dir=. watchman _artifacts/mac  --project-install-prefix watchman:/usr/local --final-install-prefix /usr/local"
      - name: Test 
        timeout-minutes: 60
        run: "python3 build/fbcode_builder/getdeps.py --allow-system-packages test --src-dir=. --num-jobs=1 watchman  --project-install-prefix watchman:/usr/local"
      - name: List
        run: ls -l _artifacts/mac
